### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by Sunbelife** [CasterWx/python-girlfriend-mood#3]
你好，发现 python-girlfriend-mood/data/MoodValue.txt 有乱码情况。

**Comment by CasterWx** [comment]
> 你好，发现 python-girlfriend-mood/data/MoodValue.txt 有乱码情况。

换一下编码 , 用GBK打开.

**Comment by MrPeterJin** [comment]
更换编码之后问题依旧，debug中读取仍然是乱码
